project_id = "trydlkeihqarjdlajzfh"

[functions.request-download]
verify_jwt = false

[functions.download-file]
verify_jwt = false

[functions.subscribe-newsletter]
verify_jwt = false

[functions.confirm-newsletter]
verify_jwt = false
